//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationCertificates
    {
        public int ID { get; set; }
        public Nullable<int> animalID { get; set; }
        public Nullable<int> VaccinesID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Vaccines Vaccines { get; set; }
    }
}
