//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationCertificate
    {
        public int ID { get; set; }
        public Nullable<int> animalID { get; set; }
        public Nullable<int> VaccinesID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
